<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-19T09:46:41Z" name="Suite" finished-at="2020-09-19T09:47:04Z" duration-ms="22999">
    <groups>
    </groups>
    <test started-at="2020-09-19T09:46:41Z" name="Test" finished-at="2020-09-19T09:47:04Z" duration-ms="22999">
      <class name="testcases.Add_Customer">
        <test-method is-config="true" signature="setup(org.testng.ITestContext)[pri:0, instance:testcases.Add_Customer@4c1909a3]" started-at="2020-09-19T09:46:30Z" name="setup" finished-at="2020-09-19T09:46:41Z" duration-ms="11433" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@de88ac6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:1, instance:testcases.Add_Customer@4c1909a3]" started-at="2020-09-19T09:46:41Z" name="login" finished-at="2020-09-19T09:46:54Z" duration-ms="12919" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="add_cust()[pri:2, instance:testcases.Add_Customer@4c1909a3]" started-at="2020-09-19T09:46:54Z" name="add_cust" finished-at="2020-09-19T09:47:04Z" duration-ms="9549" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Email is already registered]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Email is already registered
at junit.framework.Assert.fail(Assert.java:47)
at pageObjectLibrary.pob_addCustomer.add_customer(pob_addCustomer.java:95)
at testcases.Add_Customer.add_cust(Add_Customer.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_cust -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:testcases.Add_Customer@4c1909a3]" started-at="2020-09-19T09:47:05Z" name="terminate" finished-at="2020-09-19T09:47:11Z" duration-ms="5776" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- testcases.Add_Customer -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
